name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget "https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip" -O commandlinetools-linux.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip -q commandlinetools-linux.zip -d $HOME/android-sdk/cmdline-tools
        yes | $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        $HOME/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-30" "build-tools;30.0.3"

    - name: Create Cordova project
      run: |
        cordova create counterapp
        cd counterapp
        cordova platform add android
        cordova plugin add https://github.com/manueldeveloper/cordova-plugin-volume-buttons.git
        cordova plugin add cordova-plugin-background-mode

    - name: Copy application files
      run: |
        rsync -av --exclude='counterapp' . counterapp/www/
        ls counterapp/www/

    - name: Build the project with release build
      run: |
        cd counterapp
        cordova build android --release

    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: counterapp/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: error
